# Generated by Django 4.0.5 on 2023-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
